[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[[services]]
name = "pricedom"

[services.variables]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stderr"
DB_CONNECTION = "pgsql"
SESSION_DRIVER = "database"
CACHE_DRIVER = "file"
QUEUE_CONNECTION = "sync"
PHP_MEMORY_LIMIT = "512M"
PHP_MAX_EXECUTION_TIME = "600"

[services.build]
watchPatterns = [
    "**/*.php", 
    "**/*.blade.php",
    "composer.json",
    "package.json"
]